haskell/bytestring

- Data/ByteString/Builder/Internal.hs
`Builder` is currently much slower than necessary due to the
unnecessary creation of `BufferRange` values between
`BuilderStep`s. Take this example,
```haskell
import Data.Monoid
import qualified Data.ByteString.Builder as B
import qualified Data.ByteString.Lazy as L
main = do
let run = L.length . B.toLazyByteString
n = 1 * (2 ^ (28 :: Int)) -- one MB
print $ run $ putWord8N16 n
putWord8N16 :: Int -> B.Builder
putWord8N16 = loop 0
where loop s n | s `seq` n `seq` False = undefined
loop _ 0 = mempty
loop s n =
B.word8 (s+15) <>
loop (s+16) (n-16)
```
This will produce the following
([full Core](https://gist.github.com/bgamari/091e3dac9c45ee9accf1#file-slow-hs-L1)),
```haskell
Main.$wa [InlPrag=[0], Occ=LoopBreaker]
:: GHC.Prim.Word#
-> GHC.Prim.Int#
-> forall r_aKUt. …
```
> Eta expand continuation of empty

- .travis.yml
- bytestring.cabal
- tests/Properties.hs
- tests/QuickCheckUtils.hs
Quickcheck was using Lazy ByteStrings which were far too big, and the abominable performance of `transpose` was taking up a good chunk of the total testing time. This should make things run much faster.
> Fix test performance to stop Travis CI timing out.

- Data/ByteString/Char8.hs
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
> fix Char8.unwords type in module's comment

- bytestring.cabal
I'm not sure if this is an intended issue or flaw, but on GHC-7.8.3 running on an Intel i7 in linux, I could not seem to get into an interactive repl unless `-fobject-code` was also added - the `Data.ByteString.Builder.ASCII` module wasn't compiling. Here is the error for more detail: http://lpaste.net/128004
> `cabal repl` error

- Data/ByteString.hs
- Data/ByteString/Builder/ASCII.hs
- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Builder/Prim/Internal/UncheckedShifts.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Short/Internal.hs
- Data/ByteString/Unsafe.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
This assumes that `__GLASGOW_HASKELL__` is 612 or later, as well as
`base >= 4.2` (c.f. `bytestring.cabal`).
> Radically reduce #ifdefs

- bytestring.cabal
> Revert "`cabal repl` error"

- Data/ByteString.hs
- Data/ByteString/Char8.hs
The rewrite rules of `Data.ByteString.break` are currently quite fragile (see [GHC #11688](https://ghc.haskell.org/trac/ghc/ticket/11688) and #70) as they match on the `(==)` class method. Class methods call-sites at known types are subject to GHC-generated "Class Op" rewrite rules, which rewrite the call-site to a call directly to the appropriate instance's implementation. These rules fire rather early in simplification and therefore defeat `bytestring`'s `break` rule.
The usual solution here is to give each particular instance's implementation of `(==)` a name which can be specifically matched (e.g. `Int`'s `(==)` is defined in terms of `GHC.Classes.eqInt`). Unfortunately, such names were previously not available for `Word8`. This will be fixed in GHC 8.0 (as of …
> Fix break rewrite rules

- bytestring.cabal
I just released [`dlist-0.8`](https://github.com/spl/dlist/releases/tag/v0.8). I didn't test this change to `bytestring`, but I don't think it will be break anything.
> Bump test-builder dlist upper bound to 0.9

- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Builder/Prim.hs
`bytestring` currently fails to build on GHC 7.0.1 due to a very old GHC bug, [Trac #4498](https://ghc.haskell.org/trac/ghc/ticket/4498). Luckily, it's extremely easy to work around this issue by just using the old `MonoPatBinds` pragma, as Simon recommends [here](https://ghc.haskell.org/trac/ghc/ticket/4498#comment:2).
See also https://github.com/lpsmith/bytestring-builder/pull/10.
> Fix GHC 7.0.1 build by working around Trac #4498

- Data/ByteString.hs
- Data/ByteString/Char8.hs
Prelude no longer exports catch, resulting in a warning which kills the GHC
build due to -Werror.
> Fix all the problems

- Data/ByteString/Builder/Internal.hs
This was linking to the strict `ByteString` rather than the lazy `ByteString` in the haddocks.
> Fix typo in `lazyByteString` documentation

- Data/ByteString/Short.hs
- Data/ByteString/Short/Internal.hs
I took the liberty of duplicating `moduleErrorIO` since I wasn’t sure
if it makes sense to parametrize the existing one and if so in which
module the function should be placed.
> Add conversions between ShortByteString and CString

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
Noticed this while hacking on Haddock on HEAD. The existing docs render as
Now they render as
(Note that the actual docs do hyperlink `cons`, `repeat`, and `cycle` - the images above are taken of a module with just the `cons'` function in it)
> Fix Haddock quote

- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy/Internal.hs
Due to a bug in ghc, some unused imports do not yield warnings.
This commit will remove such unused imports in preparation for
the ghc bug fix (see https://ghc.haskell.org/trac/ghc/ticket/13064).
> Remove unused imports.

- Data/ByteString.hs
Also, a few ~~comments~~ questions:
* How do I replace  `pack`  with `unsafePackAddress`? Does this look right?
```
b, b' :: ByteString
b = pack [0x01, 0x02]
b' = unsafeDupablePerformIO (unsafePackAddress "\x01\x02"#)
```
If that's right, how about adding the following convenience function?
```
unsafeLiteral :: Addr# -> ByteString
unsafeLiteral = unsafeDupablePerformIO . unsafePackAddress
```
> Fix a reference to unsafePackAddress

- bench/bench-bytestring.cabal
- bench/wiki-haskell.html
Nearly all the changes in #43 have since been made in other commits. These are the only instances of trailing whitespace that remain. This change is probably a bit superfluous; I'm really only submitting it so that we can decisively close the other PR.
> Remove trailing whitespace

- Data/ByteString/Builder/Prim/Internal.hs
- Data/ByteString/Internal.hs
Single quotes in Haddock are used for references to other identifiers.
Character literals should have both the single quote and possible backslash
escaped with extra backslahes.
Ex: `@\'\\0\'@`, not `'\0'`
> Docs: properly escape character literals

- .travis.yml
- bench/bench-bytestring.cabal
- bytestring.cabal
- tests/Properties.hs
- tests/QuickCheckUtils.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
- tests/bytestring-tests.cabal
This is a variation in #178 but one that I'm a bit happier with. Tests pass locally with QC 2.10+. Lets see about CI...
> Update for QuickCheck >= 2.10

- bench/BenchAll.hs
- bench/bench-bytestring.cabal
- bench/stack.yaml
Based on work by @hsyl20. (Thanks!)
Fixes #52.
---
TODO:
> Fix benchmark build

- .travis.yml
- Data/ByteString/Builder/Prim.hs
- bytestring.cabal
- tests/Properties.hs
- tests/bytestring-tests.cabal
In primMapByteStringBounded, when the potentially needed space for
encoding one more byte (the 'bound' of the provided BoundedPrim)
is exactly equal to the free space in the output buffer, we must
fill the buffer, rather than signal BufferFull.
Otherwise, when we ask for "bounded" more bytes, no new space
is allocated, and an infinite loop follows (at least when the output is
via the direct Builder hPut).
Code that was freezing without the change, runs fine with the test
condition updated to `<=`
> ∞-loop, space==bound in primMapByteStringBounded

- Data/ByteString/Builder/ASCII.hs
- bytestring.cabal
- tests/bytestring-tests.cabal
This patch adds support for ghc-bignum package in GHC 8.12: cf https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2231
> Add support for ghc-bignum

- Data/ByteString/Internal.hs
The purpose of this PR is to clarify that we wish "to write a tight
loop that _blasts_ the list into memory" and not one that "blats" it
into memory.
Closes #230
> Fix typo, correct 'blats' to 'blasts'

- tests/Rules.hs
Don't know why I'm only seeing this with GHC master, but one more prop test started failing due to non-injective correspondence between test `Chars` and test `Word8` codepoints. This resolves the issue.
> Fix `break (==)` prop test for `Char8` bytestrings.

- Changelog.md
- Data/ByteString.hs
- Data/ByteString/Char8.hs
- tests/Properties.hs
A few notes:
* I couldn't build the benchmarks, so I haven't added benchmarks for the new functions. However their implementation is very similar to that of other functions so it shouldn't make too big a difference (though I don't know if I should inline `strip`).
* I don't know how closely `Data.ByteString.Char8` is trying to follow the functions on `String`: for instance, there is no `strip` function on `String`. Let me know whether exporting the `strip` and `dropSpace` functions is the right thing to do or not (though my motivation for adding `dropWhileEnd` and `takeWhileEnd` is to have `strip`).
* I haven't implemented `dropWhileEnd` and `takeWhileEnd` on lazy bytestrings, because (1) I don't know how much sense it makes and (2) I wouldn't know how to do that efficiently, for some …
> Add dropWhileEnd, takeWhileEnd, strip

- Changelog.md
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Short/Internal.hs
Resolves #106, as suggested by @dcoutts in #114 (and supersedes the latter). 
CC @andrewthad
> Add IsList instances

- Data/ByteString/Builder/Prim.hs
- Data/ByteString/Builder/Prim/ASCII.hs
- Data/ByteString/Builder/Prim/Internal.hs
`boudedPrim` is deprecated.
Fixes #48.
> Add D.BS.B.P.I.boundedPrim to fix typo in "boudedPrim"

- Changelog.md
One concern that frequently came up in discussions over breaking changes is that many packages currently don't specify an upper bound on `bytestring`. The note I'm adding here is meant to help remediate that situation.
The planned breaking changes I'm currently aware of are:
* #174 
* #180 
and potentially the result of #140.
> Changelog: Warn about upcoming breaking changes

- Changelog.md
- Data/ByteString/Lazy/Builder.hs
- Data/ByteString/Lazy/Builder/ASCII.hs
- Data/ByteString/Lazy/Builder/Extras.hs
It's been planned to deprecate for 8 years, so let's do this.
> Deprecate Data.ByteString.Lazy.Builder.*

- Data/ByteString/Internal.hs
> Expose D.B.Internal.{create,unsafeCreate}UptoN'

- Data/ByteString/Lazy.hs
> Fix documented complexity of Lazy.length

- bench/CSV.hs
- bench/bench-bytestring.cabal
Also, removed the benchmark for Data.Binary.Builder because it just reexports bytestring's Builder.
> bench: make CSV buildable

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- tests/Properties.hs
Fixes #56 by clarifying and documenting existing behaviour. Supersedes #94.
> Document behaviour of split and splitWith on empty input

- Changelog.md
- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Short.hs
- Data/ByteString/Short/Internal.hs
- tests/Properties.hs
This is a continuation of @FintanH's work in #146. I've rebased his commits onto the current `master`.
> Add non-throwing indexMaybe function (continues #146)

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- tests/Hash.hs
- tests/Words.hs
- tests/test-compare.hs
- tests/unpack.hs
This removes all vestiges of the `PS` constructor, other than the backwards-compatibility pattern definition.
Also fixes the commented out alternative implementation of `Data.ByteString.Char8.lines`. Perhaps worth
using instead of the current one???
> Really no offset

- Data/ByteString.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Short/Internal.hs
- bench/BenchAll.hs
- cbits/fpstring.c
- include/fpstring.h
This is similar in spirit to #123, but includes benchmarks to reproduce results. I also decided to use `qsort` from `stdlib` instead of implementing insertion sort manually, just to minimise changes.
(I have no idea about C, suggestions would be highly appreciated, CC @vdukhovni)
```
countsort
sort/zyxwvutsrq                          mean 299.7 ns  ( +- 19.84 ns  )
sort/zyxwvutsrqp                         mean 320.1 ns  ( +- 23.39 ns  )
sort/zyxwvutsrqpo                        mean 302.7 ns  ( +- 19.03 ns  )
sort/zyxwvutsrqpon                       mean 323.6 ns  ( +- 27.07 ns  )
sort/zyxwvutsrqponm                      mean 336.2 ns  ( +- 39.73 ns  )
sort/zyxwvutsrqponml                     mean 324.9 ns  ( +- 17.24 ns  )
sort/zyxwvutsrqponmlk                    mean 400.2 ns  ( +- 47.64 …
```
> Use qsort to sort short ByteString

- Data/ByteString/Builder.hs
- Data/ByteString/Builder/Prim.hs
- bench/BenchAll.hs
- bench/bench-bytestring.cabal
- tests/builder/Data/ByteString/Builder/Prim/Tests.hs
Previously `String`s would be handled with `P.primMapListBounded P.charUtf8`. In the case that the `String` was a literal, we would decode UTF-8 from the primitive string and then reencode each character as we wrote it to the target buffer. Not only was this inefficient to run, it was also inefficient to compile as we would be forced to inline and simplify large swathes of the builder machinery (see [GHC #13960](https://ghc.haskell.org/trac/ghc/ticket/13960)).
The obvious solution here is to do what we should have done all along: `strcpy` directly out of the primitive string into the target buffer. In the case of UTF-8 things are slightly trickier as we must recognize NULL characters, which GHC encodes as `0xc0 0x80`.
Fixing this is a win in several respects: code size of a trivial `main …
> [RFC] Builder: Efficiently handle literal strings

- Data/ByteString.hs
There's no need for a separate `withForeignPointer` call to subtract the
pointers after `memchr`.  The entire loop is a closure around a fixed
foreign pointer which can safely be reused with just a *single*
`withForeignPointer` in each loop iteration.
In informal measurements, this yields non-trivial performance
improvements, but even without these, the code is simply better.
> Simpler, cleaner faster `elemIndices`

- Data/ByteString.hs
- Data/ByteString/Lazy.hs
- tests/Properties.hs
> Rules for takeWhile and dropWhile

- Data/ByteString/Lazy.hs
This PR adds some implementation details about file handles in a Lazy IO context
---
cc @int-e @dminuoso @kozross
> Add comments about risks and mitigation of lazy IO

- Data/ByteString.hs
- Data/ByteString/Lazy.hs
- bench/BenchAll.hs
This is #151 rebased, see explanations there. Closes #206. CC @sergv
> Optimize folds

- bench/BenchIndices.hs
- bench/bench-bytestring.cabal
Adds a benchmark suite for measuring the performance of `Data.ByteString.findIndices` relative to `Data.ByteString.findIndex` (and the related `Data.ByteString.elemIndices` and `Data.ByteString.elemIndex`) over inlinable and uninlinable equality tests.
For comparing performance of relevant functions before and after changes implemented in #270
> Benchmark for FindIndices

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
Reimplements findIndices to iteratively call findIndex, which
yields an approximate 2x improvement over original implementation
for a simple equality predicate
Adds inline pragma for findIndices, which yields an approximate 10x
improvement for a simple equality predicate
Additionally inlines findIndices functions in
Data.ByteString{.Lazy,}{.Char8,}
resolves #269
> FindIndices optimized using findIndex and inlining

- Data/ByteString/Internal.hs
As noted in GHC #17290, ForeignPtrContents really should be strict.
With the addition of the FinalPtr constructor we now have a
sensible value to use in nullForeignPtr other than bottom.
Moreover, another unrelated GHC change (#17760) recently forced
the application of strictness for ForeignPtr's ForeignPtrContents
field. Consequently, we are making this change now. Unfortunately this
means that all earlier versions of bytestring will be unbuilable with
GHC >=9.0.
> [master] Don't fill ForeignPtrContents field with bottom

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/Internal.hs
Closes #279. 
Basically I just moved `fromStrict` / `toStrict` from `Data.ByteString.Lazy` to `Data.ByteString.Lazy.Internal`. The difficulty is that their implementation depends on `Data.ByteString.{length,null,take,drop}`. I could potentially move these four functions to `Data.ByteString.Internal`, but I decided just to operate on fields of `BS` directly. IMHO it is a better option, because it moves less stuff between modules and also shaves off a couple of picoseconds, avoiding conditional branches in `take` / `drop`.
> Expose fromStrict/toStrict directly from Data.ByteString

- Changelog.md
I think we are good to go, but will wait until the next week to upload. 
It would be nice to include #258 as well, if it is ready in time.
CC @vdukhovni @fumieval
> Prepare release 0.11.0.0

- Changelog.md
- README.md
- bytestring.cabal
1. Since we do not test against GHC 6.12, it is better to stop listing it as a supported platform (cf. discussion in #285). Thus, I changed GHC 6.12 to 7.0 in `README.md` and bumped the lower bound for base from 4.2 to 4.3. However, I decided to retain `if impl(ghc < 7)` section still - it has a chance to appear useful for a daring soul. Dunno, maybe it is better to strip it as well.
2. Following discussions elsewhere, I clarified statements about compatibility issues in `Changelog.md`. 
3. I removed `cabal-install` from build requirements: `stack` or whatever can be used as well. I also removed paragraphs about building and testing: we certainly do not want people to use `cabal install` (at the very least it should be `cabal build`), and `cabal test` does not run any tests, because they …
> Final touches for 0.11.0.0

- Data/ByteString/Lazy/Internal.hs
This implements the first point from https://github.com/haskell/bytestring/issues/55
> Specialize packBytes and packChars for empty input

- Data/ByteString/Internal.hs
After installing GHC 9.0 alpha via ```ghcup set ghc 9.0.0.20200925``` the build failure was:
```
Data/ByteString/Internal.hs:331:45: error:
• Data constructor not in scope: I# :: GHC.Prim.Int# -> Int
• Perhaps you meant ‘IO’ (imported from GHC.IO)
Perhaps you want to add ‘I#’ to one of these import lists:
‘GHC.Base’ (Data/ByteString/Internal.hs:135:1-64)
‘GHC.Exts’ (Data/ByteString/Internal.hs:138:1-44)
|
331 |     return (BS (ForeignPtr addr# FinalPtr) (I# (cstringLength# addr#)))
|                                             ^^
Data/ByteString/Internal.hs:350:35: error:
• Data constructor not in scope: I# :: GHC.Prim.Int# -> Int
• Perhaps you meant ‘IO’ (imported from GHC.IO)
Perhaps you want to add ‘I#’ to one of these import lists:
‘GHC.Base’ (Data/ByteString/Internal.hs:135:1-64) …
```
> Fix build failure under GHC-9.0

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- tests/Properties.hs
> add function dropEnd

- Data/ByteString/Builder.hs
As mentioned in #47 Builder and friends should have Show instances.
I have added a Show instance inspired by the Show instance of Set. If it should be styled differently just mention it.
If I should add any more instances just mention it.
> Adds Builder Show instance

- Data/ByteString/Internal.hs
This implements the second point from #55
> Optimize inner loop of packUptoLenBytes and packUptoLenChars

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- tests/Properties.hs
Renames `zipWith'` to `packZipWith` and exports it
Recovers test cases for `packZipWith` from comments
> A PR renaming `zipWith'` to `packZipWith` and exporting it would be welcome.
_Originally posted by @Bodigrim in https://github.com/haskell/bytestring/issues/208#issuecomment-702330104_
All test cases pass
> `zipWith'` to `packZipWith` as per #208

- Data/ByteString.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Short/Internal.hs
This should resolve #97 and cleans up the code a tiny bit
> Remove references to base430

- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- tests/Properties.hs
related to #298 
I tested the function in GHCi. 
Unfortunately I do not yet understand how to add tests to the testsuite.
I'd be great if someone could give me a point in the right direction on where to add tests.
Concerning the documentation: I described the compareLength as being O(n) (where n is the length of the ByteString). This is a bit imprecise, because it neglects the `Int` parameter entirely. However, I was not sure on how to refer to this parameter in the documentation.
> Implement Data.ByteString.Lazy.compareLength

- tests/LazyHClose.hs
- tests/Properties.hs
- tests/Rules.hs
- tests/builder/Data/ByteString/Builder/Prim/TestUtils.hs
- tests/builder/Data/ByteString/Builder/Prim/Tests.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
- tests/builder/TestSuite.hs
- tests/bytestring-tests.cabal
(Depending on `tranformers` instead of `mtl` is motivated mostly by https://github.com/haskell/mtl/pull/74)
> Assorted test-suite tweaks 

- Data/ByteString/Lazy.hs
- Consolidate RULES pragmas
- Replace `negateOrdering` with `compare EQ`.
> Tweak compareLength rules

- Data/ByteString/Internal.hs
- Data/ByteString/Lazy/Internal.hs
- tests/Properties.hs
- tests/bytestring-tests.cabal
As requested in #299 
I didn't write any test cases yet
> Implement stimes more efficiently

- Data/ByteString/Internal.hs
- bench/BenchAll.hs
GHC unlike GCC does not optimize expressions like `x == 10 || x == 11 || x == 12 || x == 13` into `x >= 10 && x <= 13` and further into `x - 10 <= 3` so I did it here manually. Turns out this optimization was already applied years ago to `Data.Char.isSpace`: https://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.Unicode.html#isSpace
I chose the `w == 0x20 || w == 0xA0 || w - 0x09 <= 4` order or terms instead of `w == 0x20 || w - 0x09 <= 4 || w == 0xA0` because it was faster on my machine. It also uses one fewer register according to the Compiler Explorer. It might be beneficial to adopt this order of terms in `Data.Char.isSpace` as well.
I also added a benchmark for `words` that uses `isSpaceWord8` a lot.
Before:
```
benchmarked words/lots of words
time                 142.2 μs …
```
> Optimize isSpace functions

- Data/ByteString/Short.hs
After #305 there remain no reasons to hide `SBS` constructor into an `Internal` module: there is no internal invariant left which could possibly violated by its exposure. 
This allows users to implement `byteArrayToByteString` and `byteStringToByteArray` from #186 without reaching out for internal modules. Cf. #253.
> Expose ShortByteString construstor

- .github/dependabot.yml
- .github/workflows/ci.yml
- README.md
Example run: https://github.com/ethercrow/bytestring/actions/runs/326555407
It actually shows that there are some issues on Windows, presumably not in the library but in the test suite.
> Configure CI via GitHub Actions

- Data/ByteString/Short/Internal.hs
- tests/Properties.hs
Resolves #186. Cf. #253. CC @chessai @andrewthad.
I'm reluctant to provide `unsafeByteArrayToByteString` in a public interface, but we can add a shortcut to create `ByteString` from a pinned `ByteArray#`. Together with #313, this gives us an efficient way to convert between `ByteArray` and `ByteString` without reaching for internal modules:
```haskell
import Data.ByteString.Short (ShortByteString(..), fromShort, toShort)
byteArrayToByteString :: ByteArray -> ByteString
byteArrayToByteString (ByteArray b#) = fromShort (SBS b#)
byteStringToByteArray :: ByteString -> ByteArray
byteStringToByteArray bs = let SBS b# = toShort bs in ByteArray b#
```
> Shortcut for pinned bytearray

- bench/BenchAll.hs
- bench/CSV.hs
- bench/bench-bytestring.cabal
The most hilarious stuff happened in 43dc70a: Windows build used to fail because of paths exceeding 256 symbols with a cryptic error message:
`Fatal error: can't create D:\\a\\bytestring\\bytestring\\bench\\dist-newstyle\\build\\x86_64-windows\\ghc-8.6.5\\bench-bytestring-0.1.0.0\\b\\bench-bytestring-builder\\build\\bench-bytestring-builder\\bench-bytestring-builder-tmp\\Data\\ByteString\\Builder\\Prim\\Internal\\UncheckedShifts.o: No such file or directory`
> Cleanup benchmarks

- Data/ByteString/Char8.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy/Char8.hs
- tests/Properties.hs
- tests/bytestring-tests.cabal
This version detects integer overflow and returns 'Nothing'.
With lazy bytestrings it will not read new chunks after an "unreasonable" number
(more than ~32kB) of leading zeros and will instead return 'Nothing'.
Tests check that maxBound and minBound are handled correctly possibly with
explicit signs (for maxBound), and that overflowing by 1, 10 and many
appended zeros all fail.
> Backport of safe readInt from streaming-bytestring

- .github/workflows/ci.yml
- tests/Properties.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
As dicovered in #311, certain tests fail for Windows build with GHC 8.10: `DeleteFile "\\\\?\\D:\\a\\bytestring\\bytestring\\tests\\qc-test-ThreadId 5": permission denied (The process cannot access the file because it is being used by another process.)`, emitted by `System.Directory.removeFile`, invoked in `Properties.hs`. 
https://github.com/haskell/bytestring/blob/a83b77853abf209e04a77348586334f82114aa38/tests/Properties.hs#L1609-L1616
It's actually amazing that these tests have worked for ages under all other platforms, because they are reference examples of lazy I/O done wrong. Clearly the file is unlinked before its content is read in full. And `bracket` is useless here, because there is no resource to capture. One must explicitly force evaluation of lazy bytestring before removing …
> Fix IO tests

- tests/LazyHClose.hs
- tests/Properties.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
- tests/bytestring-tests.cabal
This is a necessary prerequisite for #316: if we want to move tests to the `bytestring` package itself, test components should avoid packages, which depend on `bytestring`. Except replacing `test-framework` with something having smaller dependency footprint (there is a good progress on this), the only remaining offender is `directory`, which depends on `bytestring` transitively via `unix` and `Win32` packages.
This PR unties `bytestring-tests` from `directory`:
* `removeFile` can be replaced with a POSIX `c_unlink`.
* Not sure what exactly `renameFile` was meant to test in `LazyHClose.hs` (this file was not run for ages, and only recently salvaged and integrated in the test suite). If the purpose was to ensure, that a file is properly closed, opening it for write should be enough (and …
> Do not depend on directory

- .github/workflows/ci.yml
@Bodigrim @vdukhovni I've found a Github Action that runs FreeBSD inside a VirtualBox: https://github.com/vmactions/freebsd-vm
> Run CI job in a FreeBSD VM

- .hlint.yaml
- Data/ByteString.hs
- Data/ByteString/Builder.hs
- Data/ByteString/Builder/ASCII.hs
- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Builder/Prim.hs
- Data/ByteString/Builder/Prim/ASCII.hs
- Data/ByteString/Builder/Prim/Binary.hs
- Data/ByteString/Builder/Prim/Internal.hs
- Data/ByteString/Builder/Prim/Internal/Floating.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Short/Internal.hs
`haskell-language-server-0.6` enabled hlint plugin by default, so hlint suggestions became annoying. Most of them are good stuff, so I think it makes sense to get them fixed instead of muting.
> Clean up hlint suggestions

- bytestring.cabal
* The Haskell Bytestring Team (@haskell/bytestring) serves as the primary maintainer.
* Andrew Lelechenko (@Bodigrim) is the primary contact for this team.
* The CLC (@haskell/core-libraries-committee) "owns" bytestring and oversees the primary maintainers.
Closes #256.
> Update maintainer info

- bench/BenchAll.hs
- cbits/fpstring.c
SSE2 is available on every x86_64 CPU, so there is no need for a capability check.
Before:
```
benchmarked intersperse/intersperse
time                 1.127 μs   (1.104 μs .. 1.149 μs)
0.998 R²   (0.997 R² .. 0.999 R²)
mean                 1.103 μs   (1.096 μs .. 1.112 μs)
std dev              26.95 ns   (20.98 ns .. 34.21 ns)
```
After:
```
benchmarked intersperse/intersperse
time                 715.9 ns   (697.3 ns .. 730.9 ns)
0.997 R²   (0.996 R² .. 0.999 R²)
mean                 688.7 ns   (683.4 ns .. 696.8 ns)
std dev              21.36 ns   (15.97 ns .. 32.29 ns)
```
> Implement intersperse using SSE2

- Data/ByteString/Lazy/Char8.hs
- tests/Properties.hs
The Lazy `lines` function has not been `too` strict for some
time now.  The issue was resolved a day or so after the comment
was added, but the comment was inadvertently left behind.
> Drop outdated comment

- tests/Properties.hs
- tests/Regressions.hs
- tests/Rules.hs
- tests/builder/Data/ByteString/Builder/Prim/TestUtils.hs
- tests/builder/Data/ByteString/Builder/Prim/Tests.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
- tests/builder/TestSuite.hs
- tests/bytestring-tests.cabal
This is the next step to #316. Since `tasty-1.4.0.1` supports GHC 7.0, we can switch from `test-framework` to it.
> Switch from test-framework to tasty

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Short/Internal.hs
This includes changes rewriting uses of `withForeignPtr` to `unsafeWithForeignPtr` where appropriate for GHC 9.0.
> Changes for GHC 9.0

- .github/workflows/ci.yml
To check that `cbits` are compatible with `gcc-5`. This is motivated by https://github.com/haskell/bytestring/pull/202#issuecomment-757333850
https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
> Add CI build on Ubuntu 16.04

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- tests/Properties.hs
Resolves #104. Supersedes #294.
> Add missing elemIndexEnd, findIndexEnd and unzip

- Data/ByteString.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- bench/BenchAll.hs
Closes #334 
I am open to other suggestions for the section name "Internal indexing".
> Deduplicate findIndexOrEnd by exporting it from Data.ByteString.Internal

- bench/BenchAll.hs
Adds some (not necessarily well-thought out) benchmarks for `findIndex`.
> Add findIndex benchmarks

- Data/ByteString.hs
- bench/BenchAll.hs
This makes the suggested change from https://github.com/haskell/bytestring/issues/338 so that constant arguments are not passed to helper functions.  Here are the benchmarks for findIndex and findIndexEnd:
```
old:
findIndex1/findIndices                   mean 556.2 ns  ( +- 8.501 ns  )
findIndex1/find                          mean 645.2 ns  ( +- 8.517 ns  )
findIndex1End/findIndexEnd               mean 9.832 ns  ( +- 115.2 ps  )
findIndex1End/elemIndexInd               mean 557.8 ns  ( +- 8.507 ns  )
```
```
new:
findIndex1/findIndices                   mean 526.4 ns  ( +- 12.05 ns  )
findIndex1/find                          mean 416.7 ns  ( +- 6.734 ns  )
findIndex1End/findIndexEnd               mean 9.355 ns  ( +- 111.5 ps  )
findIndex1End/elemIndexInd               mean 477.8 ns  ( +- …
```
> Optimize findIndex, findIndexEnd and map

- bench/BenchAll.hs
- bench/BenchBoundsCheckFusion.hs
- bench/BenchCSV.hs
- bench/BenchIndices.hs
- bench/bench-bytestring.cabal
I noticed that `cabal bench` tends to run all four benchmarks in parallel, with makes results quite useless. This PR works around this deficiency, unifying all benchmarks under the same umbrella to produce a single executable. It also improves linking times.
> Combine all benchmarks into a single executable

- .github/workflows/ci.yml
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Internal.hs
- cabal.project
The latest `haskell/actions` introduce GHC 9.0 as a `latest` version and displays build warnings alongside with changes. The first change has broken our Windows build, because `hcs2hs` has not yet been revised for GHC 9.0. The second change means that we need to clean up all existing warnings - otherwise they are repeated many-many times.
> Adapt to GHC 9.0 and latest haskell/actions

- Changelog.md
- bytestring.cabal
Since GHC 9.0 is finally out, and `bytestring-0.11` is incompatible with it because of a CPP issue (fixed in #293), I think it is a good time to make the next release in `0.11` series, which can be actually built with GHC 9.0. 
Changelog seems to be up to date, so this PR only bumps version in the cabal file. If it looks good, I'll merge, cherry-pick to `bytestring-0.11` branch and release.
> Release 0.11.1.0

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Unsafe.hs
[As agreed elsewhere.](https://github.com/haskell/bytestring/pull/364#discussion_r583489239)
> Remove unnecessary comments.

- Data/ByteString/Builder/ASCII.hs
- bytestring.cabal
> Remove integer-gmp / ghc-bignum dependency

- .gitignore
- Data/ByteString.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Internal.hs
> Add StrictByteString & LazyByteString type aliases

- bench/BenchAll.hs
- bench/BenchCount.hs
- bytestring.cabal
- cbits/fpstring.c
- tests/Properties/ByteString.hs
This provides a fairly significant performance boost: `count`ing lines via `BS.count 10` was taking about 1.1 s with an `mmap`ed 1.8 gigabyte file, and now it takes 0.35 s. For comparison, `length . BS.lines` takes about 0.4 s (IMO `count` should definitely be at least as fast), and Unix `wc` takes about 0.3-0.4 s.
> Implement `count` with SSE 4.2 and AVX2

- .github/workflows/ci.yml
I messed up in #386: apparently GitHub Actions allow relaxed version (e. g., `@v1`, `@v2`) only for "stable" packages, but until an action reaches `@v1`, you can use neither `@v0` nor `@v0.1`, but only `@v0.1.4`.
Seems the failure was shadowed by usual Windows stuff, and I missed email notification before too late. Sorry for this.
> Pin freebsd-vm to 0.1.4

- .hlint.yaml
- Data/ByteString.hs
This pull request changes the fold functions of the form: `fold f z bs` to `fold f z = \bs -> ...` fixing issue https://github.com/haskell/bytestring/issues/329.
On my machine it looked like this significantly improved the folds benchmarks but I am unsure if that is because I was running in a noisy environment or some other reason e.g.
Before:
```
benchmarked Data.ByteString.Builder/folds/foldl'/32768
time                 120.4 μs   (117.8 μs .. 124.2 μs)
0.993 R²   (0.986 R² .. 0.997 R²)
mean                 121.9 μs   (120.3 μs .. 124.0 μs)
std dev              6.364 μs   (5.074 μs .. 7.591 μs)
variance introduced by outliers: 31% (moderately inflated)
benchmarked Data.ByteString.Builder/folds/foldl'/65536
time                 233.3 μs   (230.9 μs .. 237.1 μs)
0.998 R²   (0.996 R² .. …
```
> Convert folds to take two arguments

- .github/workflows/ci.yml
- cabal.project
Try building tests several times to workaround an intermittent failure with a temporary file in #370. 
And we no longer need to use `cabal.project`, `hsc2hs` has been revised.
> Workaround CI failures on Windows

- Data/ByteString.hs
- Data/ByteString/Internal.hs
- bench/BenchAll.hs
This follows the approach described in #350 to optimize `unfoldrN` to float out `p` and use `pokeByteOff`
> Hand SAT optimization for Data.ByteString.unfoldrN

- Data/ByteString/Lazy/Internal.hs
- tests/Properties/ByteString.hs
Test for https://github.com/haskell/bytestring/issues/393
> Add test for #393

- Data/ByteString.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Unsafe.hs
As pointed out by @bgamari at https://gitlab.haskell.org/ghc/ghc/-/snippets/2920 and https://gitlab.haskell.org/ghc/ghc/-/issues/19557#note_357737
> Use unsafeWithForeignPtr in Data.ByteString.Unsafe

- tests/builder/Data/ByteString/Builder/Prim/TestUtils.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
This PR adds floating point tests for `floatDec` and `doubleDec`. It expects [implementations](https://github.com/haskell/bytestring/pull/365) to match base `show` functionality wrt rounding and (non) shortest-path.
These are based on the [original C tests](https://github.com/ulfjack/ryu/tree/master/ryu/tests) with modifications to match `show`.
> Floating point conversion tests

- Data/ByteString.hs
- tests/Properties/ByteString.hs
Despite FilePath being a type alias for String, the type is actually
quite distinct. An argument of type FilePath is expected to be encoded
using the file system encoding, which, by default, can be converted to a bytestring and
back exactly.
There already exist many incorrect re-implementations of these functions, usually assuming that the bytestrings should be UTF-8 encoded. [1]
I feel like having something more discoverable here might provide some value. What do you think?
> Add conversion routines for FilePath

- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/Internal/Deque.hs
- bytestring.cabal
- tests/Properties/ByteString.hs
Fixes #306.
Utilizes an eager strategy as described in the original issue. Chunks
are eagerly evaluated but the overall structure and pointers are kept
intact.
> Add lazy dropEnd and friends

- Data/ByteString/Builder.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
#406 
Some questions:
- Should I replicate `hPutBuilder` tests? Seems like  a repetition
- Should I add `readFile` as well to better align the API? If yes I could add roundtrip tests similarly to the other modules
> Add writeFile for `Builder`

- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- bench/BenchAll.hs
- tests/Properties.hs
- tests/Properties/ByteString.hs
> Straighten folds and scans.

- Data/ByteString.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
> Remove misleading outdated mentions of fusion

- bytestring.cabal
Remove upper bound on `dlist` (outdated).
The predominant style seems to not have bounds, so I removed the upper bound rather than replacing it by < 1.1.
(Maintainers: check whether this is indeed within the spirit of this package.)
Build with the latest `dlist`, dlist-1.0.  The changes in dlist-1.0 (removal of eliminator `list`, change of `tail`) do not affect the use of dlist in `bytestring`, namely in the `test-builder` test-suite.
> Remove upper bound on dlist (outdated)

- Data/ByteString/Builder/Prim/Internal/Base16.hs
While working on https://gitlab.haskell.org/ghc/ghc/-/issues/19661 I've found that this could be optimized.
> Perf: use static table for Base16

- bench/BenchCSV.hs
- bytestring.cabal
- tests/builder/Data/ByteString/Builder/Tests.hs
As discussed in #419, just to shave a dependency. A bit faster cold builds, a bit more robust solver.
> Do not depend on dlist in tests/benchmarks

- bytestring.cabal
- tests/Properties/ByteString.hs
- tests/builder/Data/ByteString/Builder/Prim/TestUtils.hs
Tested with 
```sh
apt install -y docker.io
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --rm -i -t s390x/ubuntu
```
and then in s390x virtual machine:
```sh
apt update
apt install -y ghc cabal-install git
git clone https://github.com/haskell/bytestring
cd bytestring/
cabal new-update
cabal -j1 new-test test:test-builder
```
In an emulated environment it takes three hours to build, so at some point it appeared faster to scrap `dlist` dependency than build it :)
> Fix detection of endianness in test suite

- Changelog.md
- Data/ByteString.hs
- Data/ByteString/Builder.hs
- Data/ByteString/Builder/Prim.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Lazy/Internal/Deque.hs
- Data/ByteString/Short/Internal.hs
We might wish to make a release before GHC 9.4 feature freeze, so bringing changelog into order.
> Update changelog and since pragmas

- .github/workflows/ci.yml
It appears #365 is not compatible with an upcoming GHC 9.2. It would be better to learn it earlier, so adding a CI configuration.
> Add GHC 9.2 RC1 to CI

- bytestring.cabal
- tests/builder/Data/ByteString/Builder/Prim/TestUtils.hs
- tests/bytestring-th.hs
- tests/is-valid-utf8/Main.hs
Similar to #420, we can shave a dependency (in fact two: `tasty-hunit` + `call-stack`) to speed up builds a tiny bit. I'm experimenting with `bytestring` under an emulated s390x machine, and every little helps.
> Do not depend on tasty-hunit in tests

- bytestring.cabal
- cbits/aarch64/is-valid-utf8.c
This addresses #417, specifically regarding a NEON SIMD implementation. I haven't benchmarked this (there aren't any for UTF-8 encoding and decoding specifically), but this implementation is based on the same principles as the ones used for the x86 ones, and should be fairly fast.
I also had to bump the Cabal version requirements to 2.2, so that I could use `elif` without it erroring.
On a related note: _should_ there be some benchmarks for validator speed? If so, which data should we test against?
> Aarch64 optimized UTF-8 validator

- Data/ByteString.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Short/Internal.hs
This mimics recently approved https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6772/diffs
> Add HasCallStack

- cbits/is-valid-utf8.c
- cbits/x86/is-valid-utf8.c
As discussed in https://github.com/haskell/bytestring/pull/423#issuecomment-940388720, this code appeared problematic on big-endian platforms and was commented out:
https://github.com/haskell/bytestring/blob/36874c3b6940f36cb89a4e5631204d6e59984e48/cbits/is-valid-utf8.c#L59-L83
This PR fixes it for big-endian platforms and uncomments this code. It is tested by CI jobs: i386, arm32 and ppc64le on behalf of little-endian systems without vectorized instructions and s390x on behalf of big-endian systems. 
CC @vdukhovni @kozross
> Uncomment happy path for ASCII validation and fix big-endian issues

- Data/ByteString/Short.hs
- Data/ByteString/Short/Internal.hs
- tests/IsValidUtf8.hs
This PR adds support Data.ByteString.Short.isValidUtf8 to give ShortByteString the same treatment as ByteString.
> Add Data.ByteString.Short.isValidUtf8

- Changelog.md
- Data/ByteString/Char8.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy/Char8.hs
- Data/ByteString/Lazy/ReadInt.hs
- Data/ByteString/Lazy/ReadNat.hs
- Data/ByteString/ReadInt.hs
- Data/ByteString/ReadNat.hs
- bench/BenchAll.hs
- bench/BenchReadInt.hs
- bytestring.cabal
- tests/Properties.hs
- tests/Properties/ByteString.hs
Some applications want to read either unsigned or explicitly 64-bit integers
(e.g. warp).  Provide the missing interfaces.  Based on a suggestion by @Bodigrim the code has been moved to a single module enabling simpler maintenance and reduced duplication. A very helpful nudge...
> Implement `readNatural` plus `readInt` and `readWord` for 8, 16, 32, 64 bit and native machine bit sizes

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Internal.hs
This prevents the instance object from being used as a loop-breaker.
Fixes #457.
> Break recursion in the (Monoid ByteString) instance

- README.md
Matrix Builder does not appear to be maintained.
> README (remove matrix link)

- Data/ByteString.hs
- bench/BenchAll.hs
One thing that seems suspicious was that there's supposedly efficient `intercalateWithByte`, but it only works on two strings.
This PR takes the approach from `intercalateWithByte` to `intercalate`. Unfortunately there are not any benchmarks for either function so I don't know where the performance claims of `intercalateWithByte` come from.
> Rewrite intercalate in a more direct way

- Data/ByteString.hs
With #459 merged, the size-related arithmetic in `intercalate` now needs its own overflow-detection separate from that in `concat`, and the INLINE phase markers related to the removed `intercalateWithByte` rule are no longer necessary.
> intercalate-related cleanup

- Data/ByteString/Char8.hs
The documentation comment for `dropWhileEnd` in `Data/ByteString/Char8.hs` refers to `dropWhileEnd` as `dropWhile`.  This fixes that.
> Data.ByteString.Char8: Fix doc comment for dropWhileEnd.

- Data/ByteString/Char8.hs
- Data/ByteString/Lazy/Char8.hs
- bench/BenchAll.hs
- tests/Properties.hs
Fixes #476 
Benchmark results:
before:
```
lazy-unlines: OK (0.30s)
547  μs ±  34 μs, 3.2 MB allocated,  23 KB copied,  38 MB peak memory
```
after:
```
lazy-unlines: OK (0.20s)
354  μs ±  24 μs, 2.0 MB allocated,  23 KB copied,  38 MB peak memory
```
> Lazier unlines

- Data/ByteString/Char8.hs
- Data/ByteString/Lazy/Char8.hs
Closes #478.
I wanted to share some code between strict `unlines` and strict `intercalate`, but wasn't able to easily get the singleton-copying to rewrite to a `poke` or similar, resulting in a performance hit. I think this level of duplication is acceptable.
My idea to make `Lazy.concat` fuse with the existing lazy `unlines` definition was a slight improvement, but just writing the fused fold manually produced bigger gains. I think this is because now no attempt is made to iterate over a singleton.
Benchmark results:
master:
```
unlines
lazy:   OK (0.94s)
854  μs ±  17 μs
strict: OK (0.74s)
688  μs ±  13 μs
```
topic branch:
```
unlines
lazy:   OK (19.72s)
599  μs ± 4.7 μs
strict: OK (68.04s)
249  μs ±  18 μs
```
> Implement 'unlines' directly

- Data/ByteString/Builder/RealFloat/Internal.hs
> Fix build with GHC 9.2 on i386

- .github/workflows/ci.yml
- cbits/fpstring.c
- cbits/is-valid-utf8.c
Closes #481. The approach is a bit heavy-handed (basically, CentOS 7 gets no SIMD UTF-8 stuff at all), but the fallback _should_ still be fairly fast. I've also implemented [Bodigrim's suggestion](https://github.com/haskell/bytestring/issues/481#issuecomment-1029464445) as part of this to ensure that `fpstring.c` can also build.
Ping for @hasufell and @Bodigrim.
> Repair cbits on CentOS 7

- Data/ByteString.hs
- Data/ByteString/Short/Internal.hs
> Use safe isValidUtf8 for large inputs

- Changelog.md
Given that #486, #487 and #490 has been merged, we can try and make a new release before GHC 9.2.2. @sjakobi what do you think? CC @bgamari @hasufell
> Update changelog for bytestring-0.11.3.0

- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Short/Internal.hs
- README.md
- bench/BenchAll.hs
- tests/Properties.hs
After making [this comment](https://github.com/haskell/bytestring/pull/410#issuecomment-979268852), I was a bit disappointed to discover that the existing `Semigroup` instances for `StrictByteString` and `ShortByteString` were also memory-unsafe in the presence of `Int` overflow. Here's a quick pass adding some overflow checks where they are necessary, along with a couple of other related small improvements.
> Improve memory-safety of Semigroup instances

- .drone.yml
Thanks to @AlistairB there are now official Docker images for arm64, covering GHC 8.10, 9.0 and 9.2. 
I suspect the failure in GHC 9.2.1 build is caused by known issues with arm code generator, so this PR will remain a draft until GHC 9.2.2.
> Use official Docker images for arm64

- bytestring.cabal
Follow-up to #500, which removed the gcc_s extra-library dependency.
> Remove outdated comments on Windows extra-libraries

- cbits/fpstring.c
- cbits/is-valid-utf8.c
Closes #504. 
See https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/ChangeLog;h=06ebfb1a548abc36a464ec713c33232c3c872baf;hb=91c632c88994dca583bcd94e39cd3eba1506ecfe and https://github.com/haskell/text/pull/407
> __get_cpuid_count was introduced in gcc 6.3

- Data/ByteString.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Short/Internal.hs
The inline doc for `drop  :: Int -> ByteString -> ByteString` states that it can return `[]`. 
This is mistaken, and is likely due to copying documentation from `Data.List`.
> correct `drop` documentation

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
In the same spirit as #509, I found a few more places where lists snuck into the docstrings where they should be strings or ByteString.
> de-list documentation

- bytestring.cabal
This is no longer appropriate with GHC-9.4's clang-based toolchain.
> Don't link against libgcc on Windows with GHC 9.4+

- Data/ByteString.hs
> Simplify useAsCString

- bytestring.cabal
Otherwise with `tasty-quickcheck-0.8.0.3` we get
```
[ 8 of 15] Compiling QuickCheckUtils [Test.Tasty.QuickCheck changed]
tests/QuickCheckUtils.hs:107:32: error:
Not in scope: type constructor or class ‘Gen’
|
107 | sizedShortByteString :: Int -> Gen SB.ShortByteString
|                                ^^^
```
> Add lower bound for tasty-quickcheck

- Data/ByteString/Builder/Prim/Binary.hs
We do this by swapping the byte order in memory before we write.
This speeds up int64BE by about a factor of three on my machine (skylake).
`int16BE` hardly changes, i guess the write buffer is not a bottle neck for 16bit words. But beyond that it makes a large difference.
Before
```
int16BE (10000):                                          OK (0.54s)
7.68 μs ± 215 ns
int32BE (10000):                                          OK (0.43s)
11.6 μs ± 342 ns
int64BE (10000):                                          OK (0.42s)
22.7 μs ± 669 ns
word16BE (10000):                                         OK (0.55s)
7.68 μs ± 218 ns
word32BE (10000):                                         OK (0.42s)
11.6 μs ± 355 ns
word64BE (10000):                                         OK (0.42s)
22.7 μs ± 728 …
```
> Builders: Implement non-host endianess writes using a single write.

- Changelog.md
- Data/ByteString/Short/Internal.hs
I noticed the function got removed in 731caea but there's no trace of that in the changelog, which probably makes it an accidental omission.
> Export ‘unsafeIndex’ on short bytestrings

- Data/ByteString/Builder/Prim.hs
I think this was an oversight in https://github.com/haskell/bytestring/commit/155bf8ae5d25c1cac33a0a5021c1709fbd8e23e7
The bufferFull signal takes the _minimum_ number of required space to make progress. Instead, the defaultChunkSize was used. I can't prove it yet but I have a hunch this is causing https://github.com/yesodweb/wai/issues/894. It looks like defaultChunkSize is 32k. A Warp buffer is something around 16k thus it will always hit the bufferFull signal when writing a cstring/cstringUtf8 requiring a bigger buffer which then makes Warp error out.
Pinging @bgamari as he is the author of the aforementioned patch and @basvandijk, maybe you can try out this fix and see whether it's fixing your issue?
> Bugfix: Correct minimum required bounds for serializing cstring and cstringUtf8

- Data/ByteString/Internal.hs
- Data/ByteString/Short/Internal.hs
One of these was demonstrated by haskell/aeson#967 and [GHC issue 22204](https://gitlab.haskell.org/ghc/ghc/-/issues/22204).
I took the liberty of auditing the rest of our use-sites for `accursedUnutterablePerformIO`. The uses I haven't removed in this commit perform only read effects, which are at least less dangerous.
> Remove two bad accursedUnutterablePerformIO uses

- Data/ByteString/Short/Internal.hs
- bench/BenchShort.hs
Following the discussion from https://github.com/haskell/bytestring/issues/524#issuecomment-1173126905
Before:
```
$ cabal run -w ghc-9.2.3 --enable-profiling bytestring-bench --ghc-options='-fcheck-prim-bounds -fno-ignore-asserts' -- -p 'unpack' +RTS -s
Up to date
All
ShortByteString
ShortByteString unpack
unpack and look at first 100 elements: OK (0.87s)
55.6 ms ± 4.8 ms,  66 MB allocated, 242 B  copied, 181 MB peak memory
unpackLast:                          OK (0.99s)
63.1 ms ± 5.2 ms,  66 MB allocated, 226 B  copied, 181 MB peak memory
All 2 tests passed (1.96s)
2,246,950,896 bytes allocated in the heap
7,568 bytes copied during GC
71,372,544 bytes maximum residency (29 sample(s))
1,339,648 bytes maximum slop
181 MiB total memory in use (0 MB lost due to fragmentation)
Tot time …
```
> Speed up Data.ByteString.Short.unpack

- .drone.yml
Seems drone.io no longer offers 32-bit ARM machines.
> Remove ARM 32bit job

- .github/workflows/ci.yml
- Changelog.md
- Data/ByteString/Short/Internal.hs
- bytestring.cabal
`ByteArray` has just landed into GHC HEAD: https://gitlab.haskell.org/ghc/ghc/-/commit/1f8090933268b1ca071bc4a8a35b0f1828a76fce
This awaits for https://github.com/haskell/deepseq/pull/65
> Switch Data.ByteString.Short to ByteArray

- Data/ByteString/Internal/Type.hs
Otherwise, GHC may try to share the intermediate Integer between calls to the function with one argument.  This is usually terrible for performance; in any rare case where it is beneficial the programmer can still perform such sharing themselves.
I gave a bit more detail in this comment: https://github.com/haskell/bytestring/issues/493#issuecomment-1129450195
Floating the `where` block into the body of the lambda is also possible, but is uglier and IIRC also has no effect on the generated interface file.
> Re-increase arity of stimesPolymorphic

- Data/ByteString/Short/Internal.hs
- bytestring.cabal
The spurious incomplete-pattern-match warnings from CI are a bit distracting. Let's get rid of them.
> Silence warnings in Data.ByteString.Short.Internal

- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Internal/Deque.hs
- bench/BenchAll.hs
- bench/BenchIndices.hs
- bench/BenchShort.hs
- tests/Properties.hs
- tests/Properties/ByteString.hs
- tests/QuickCheckUtils.hs
This is to facilitate my work on https://github.com/haskell/core-libraries-committee/issues/87, but probably not bad even on its own. 
The only change in library's source code is 
```diff
-        inits' (Chunk c cs) = List.map (`Chunk` Empty) (List.tail (S.inits c))
+        inits' (Chunk c cs) = List.map (`Chunk` Empty) (List.drop 1 (S.inits c))
```
which could be nicer if we had #552 in place.
> Avoid Prelude.head and Prelude.tail

- Data/ByteString/Lazy.hs
...at least for the second component of its result. The thunk for the first component is a bit hairier because the readWord8OffAddr# is considered a side effect by GHC and hence can currently never go away unless it is used lazily.
See also #558.
> Prevent Lazy.uncons from allocating a thunk

- Data/ByteString.hs
- Data/ByteString/Char8.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Char8.hs
- bench/BenchAll.hs
- tests/Properties/ByteString.hs
See #552.
The lazy versions use new implementations:
- Lazy `tails` got about 10% faster. (A happy accident!)
- Lazy `inits` got much faster:
- For the first few chunks it is about 50% faster, due to better fusion.
- When there are many chunks it is about 2.5x faster.
The performance of the strict versions is unchanged. The `inits` benchmark with small chunks is on the slow side, taking a little over 100ms on my machine.
> Add NonEmpty variants of inits and tails

- .github/workflows/ci.yml
Inspired by https://github.com/haskell/unix/pull/266
> Fix CI on Ubuntu 22.04

- .github/workflows/ci.yml
- Data/ByteString/Internal/Type.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Internal.hs
- tests/Properties/ByteString.hs
- tests/QuickCheckUtils.hs
More specifically, the idea is to make every call to `Chunk` check the invariant, at least in the bounds-checking job.
> Check the no-empty-chunks invariant in CI

- .github/workflows/ci.yml
* Add Ubuntu + GHC 9.6 job.
* Extend Windows matrix with GHC 9.2 (to test GCC interaction) and GHC 9.4 (to test Clang 13.0, see https://github.com/haskell/bytestring/pull/582#issuecomment-1520579131).
> Extend CI matrix

- Data/ByteString/Builder/Internal.hs
It might be nice to work out how much this affects the balance of power between trimming and not trimming. But it's a nice incremental improvement without that.
> Builder: Re-use the old buffer after trimming

- Data/ByteString/Builder/Internal.hs
I had difficulties reviewing #581 and ended up annotating things with explicit type signatures. I guess it does not hurt to submit them for the sake of future reviewers.
> Add type signatures for subfunction of `buildStepToCIOS`

- Data/ByteString.hs
- Data/ByteString/Internal.hs
- Data/ByteString/Internal/Type.hs
- Data/ByteString/Short/Internal.hs
By removing the `lazy` from the implementation of `unsafeDupablePerformIO`, this patch allows the simplifier to unbox intermediate `StrictByteString`s in many more situations.
This improved freedom for the simplifier comes at a price: It creates opportunities for the simplifier to perform reads at the newly-unboxed addresses before the buffer has actually been initialized. To prevent this from causing problems, the `deferForeignPtrAvailability` function is introduced. (I'm not _entirely_ sure this provides enough protection in a multi-threaded context on all architectures. Maybe @bgamari can comment? But it's at least no more unsafe than the `ShortByteString` stuff already is.)
Supersedes #466.
> Allow the result of unsafeCreate to be unboxed

- Changelog.md
(noticed while verifying every 0.11.5 item was already backported)
> Changelog: fix module for create*

- cbits/is-valid-utf8.c
Fixes #601.
I haven't worked out how to reproduce the problem (outside of GHC's CI), but that doesn't seem critical. (And this patch **[does](https://gitlab.haskell.org/ghc/ghc/-/pipelines/82426)** fix the problem there.)
> Avoid __builtin_ctzll on some platforms

- Changelog.md
- bytestring.cabal
With #601 resolved I think we should make a patch-level 0.11.5.1 release so that ghc can use it in their stable branches.
I'm not sure it's worth bothering with an announcement. This should happen very soon if we want to catch 9.4.6.
> Prepare 0.12.0.1 release

- cbits/is-valid-utf8.c
The Rts.h include seems to cause build problems.
See also:
https://gitlab.haskell.org/ghc/ghc/-/issues/23789
https://github.com/haskell/bytestring/issues/606
> Use a more specific include than Rts.h

- Changelog.md
- bytestring.cabal
See [ghc issue 23789](https://gitlab.haskell.org/ghc/ghc/-/issues/23789).
> Prepare 0.12.0.2 release

- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Internal/Type.hs
- Data/ByteString/Short/Internal.hs
- tests/Properties/ByteString.hs
- tests/builder/Data/ByteString/Builder/Tests.hs
I implemented `stimes` for `Builder` in #587 after being unpleasantly not-quite-surprised by the fact that it doesn't work with a multiplier of zero in the tests I wrote in that patch. But the change is unrelated, so I've broken it off into another pull request.
We could also now newtype-derive `Semigroup` and `Monoid` for `ShortByteString` with base-4.18 and newer, but I haven't done so yet because I'm undecided on whether that should be considered a breaking change for PVP purposes: It would change the types of errors we throw on overflow from our own `SizeOverflowException` to whatever `Data.Array.Byte` chooses to throw. (Error message quality is about the same in both cases, I think.)
> Implement stimes for Builder and ShortByteString

- Data/ByteString.hs
- bytestring.cabal
Greetings all
Per the closed discussion in #193 — code-change won't be happening, but documentation may get improved.
Here I'm submitting a paragraph near the top of `Data.ByteString` module reiterating the points made in `Data.ByteString.Short` section on memory fragmentation. The idea is to simply advertise `ShortByteString` from the package entry-point.
Having been caught in this caveat myself — I can definitely reflect that the mention of `ShortByteString` from package header (cabal description), was hard to notice.
@Bodigrim please review? Wording nitpicks, feedback, etc — totally welcome. Would appreciate an approve to merge, thanks in advance.
> Doc patch: link to ShortByteString from ByteString module

- Data/ByteString.hs
- Data/ByteString/Short/Internal.hs
Following up on https://github.com/haskell/unix/issues/295#issuecomment-1718073596.
> Document that useAsCStringLen does not append NUL

- Data/ByteString/Short/Internal.hs
`Data.ByteString.Short.Internal` defines:
```haskell
data BA = BA# ByteArray#
```
This type is equivalent to `ByteArray` from `Data.Array.Byte`, which is already used in `Data.ByteString.Short.Internal`.
This PR removes the `BA` data type in favor of `ByteArray`.
> Remove `Data.ByteString.Short.Internal.BA`

- Data/ByteString/Short/Internal.hs
> Remove `Data.ByteString.Short.Internal.MBA`

- cbits/aarch64/is-valid-utf8.c
- cbits/is-valid-utf8.c
- tests/IsValidUtf8.hs
Fixes #620.  We must roll back some if the last SIMD block contains an incomplete multi-byte code point.  The old logic for this would roll back by one even if there were zero SIMD blocks processed, which is exactly the bug.
> Tweak UTF-8 validation 'roll back' logic

- Data/ByteString/Builder.hs
Remove redundant imports and the redefinition of (<>).
> Minor update to ByteString Builder Haddock tutorial

- Data/ByteString/Builder/Prim/Internal/Base16.hs
This seems to exist for no reason, and prevents case-of-known-constructor from eliminating an indirection in downstream modules.
> Remove NOINLINE on lowerTable

- .github/workflows/ci.yml
The windows jobs were subtly broken by #613, which caused the build products to live in bytestring-*/dist-newstyle instead of dist-newstyle.  This didn't appear to break immediately because we restored cached stuff in dist-newstyle including stale executables.  It wasn't until a week of inactivity caused our cache to expire that the breakage became appropriately obvious.
I don't really understand what went wrong with the centos job; I just borrowed the workaround from haskell/text#541.
> Attempt to fix CI again

- Data/ByteString/Builder.hs
- Data/ByteString/Builder/ASCII.hs
- Data/ByteString/Builder/Extra.hs
- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Builder/Prim.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Lazy/Internal/Deque.hs
While using qualified names such as `S.ByteString` or `L.ByteString`
allows for GHC to disambiguate between the strict and lazy variants, the
generated haddocks end up being quite confusing, prime examples being
`fromStrict` and `toStrict`.
This patch replaces such uses with the type synonyms `StrictByteString` and `LazyByteString` to (hopefully) make the docs a bit clearer.
> Use the strict/lazy type synonyms for better generated documentation

- Data/ByteString/Builder/Prim/Internal.hs
It is poorly documented and dangerous with respect to alignment and internal padding. It is exposed only via the semi-internal module Data.ByteString.Builder.Prim.Internal, and has no users on Hackage. (Since #587 we do not use it internally.)
> Deprecate storableToF

- Data/ByteString/Utils/UnalignedWrite.hs
- include/bytestring-cpp-macros.h
I'm in no rush to land this. The "right" CPP condition won't work until upstream bumps their version numbers and anyway it might be nice to let the other implementations from #587 get tested more widely in 9.10.1-alpha1 first.
> Use primops for unaligned writes when possible

- Data/ByteString/Builder/Internal.hs
- Data/ByteString/Short/Internal.hs
Since `stimes` was explicitly implemented in #611: Closes #488. Closes #489.
> Explicitly implement `sconcat` in Semigroup instances

- .github/workflows/ci.yml
- Data/ByteString/Internal/Type.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Short/Internal.hs
- bytestring.cabal
- tests/Properties/ByteString.hs
See [here](https://github.com/clyring/bytestring/compare/7e11412b9bfb13bcd6b8e7c04765b8f5bd90fd34..backport-614) for an illustration of how this differs from the original patch.
> Backport: Implement instance Data (#614)

- Data/ByteString/Short.hs
- Data/ByteString/Short/Internal.hs
> doc: Fix haddocks in Data.ByteString.Short

- cbits/shortbytestring.c
See #653.  A complete audit has not been done,
but let's just fix the known bug anyway.
> Fix known type mismatch in sbs_elem_index

- Data/ByteString/Short/Internal.hs
This ensures that the result of `fromShort` is properly protected by a call to `mkDeferredByteString`.
> Use `BS.unsafeCreateFp` in `fromShort`

- Data/ByteString/Builder/Prim/Binary.hs
- Data/ByteString/Builder/RealFloat/Internal.hs
- Data/ByteString/Utils/ByteOrder.hs
- bytestring.cabal
I can't be bothered to remember the right combination of `#include ...` and `#ifdef` to check this. So I'd like to remove the need entirely.
> Move all endianness/byte-order CPP into one module

- .gitignore
- Data/ByteString/Builder/ASCII.hs
- Data/ByteString/Builder/Prim/ASCII.hs
- Data/ByteString/Builder/Prim/Binary.hs
- Data/ByteString/Builder/RealFloat/Internal.hs
- Data/ByteString/Internal/Pure.hs
- Data/ByteString/Internal/Type.hs
- Data/ByteString/Short/Internal.hs
- Data/ByteString/Utils/ByteOrder.hs
- Data/ByteString/Utils/UnalignedAccess.hs
- bytestring.cabal
- cbits/fpstring.c
All of these were standard C functions that GHC's JS backend actually somewhat supports; their shims can be found in the compiler source at "rts/js/mem.js". But it seems simpler to just get rid of all FFI uses with -fpure-haskell rather than try to keep track of which functions GHC supports.
The pure Haskell implementation of memcmp runs about 6-7x as fast as the simple one-byte-at-a-time implementation for long equal buffers, which makes it... about the same speed as the pre-existing shim, even though the latter is also a one-byte-at-a-time implementation!
Apparently GHC's JS backend is not yet able to produce efficient code for tight loops like these yet; the biggest problem is that it does not perform any loopification so each iteration must go through a generic-call indirection. …
> Remove remaining uses of FFI under -fpure-haskell

- Data/ByteString/Lazy/Internal.hs
Looking at a test coverage report brought it to my attention.
(Somehow this was missed in #590.)
> Remove another dead branch from toStrict

- .github/workflows/ci.yml
...as suggested by @Bodigrim in https://github.com/haskell/bytestring/pull/669#issuecomment-2046127846.
> Bump actions/checkout to v4 in CI

- Data/ByteString/Builder/Internal.hs
- bench/BenchAll.hs
...separated out from #569. The main improvement is that this separates the buffer allocation cost (which is similar for all `Builder`s) from the actual write/encoding cost.
> Improve benchmarks for small Builders

- .github/workflows/ci.yml
- Data/ByteString/Internal/Type.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Short/Internal.hs
- Data/ByteString/Unsafe.hs
- Data/ByteString/Utils/ByteOrder.hs
- README.md
- bytestring.cabal
- cbits/shortbytestring.c
- include/bytestring-cpp-macros.h
Along the way:
* Obseleted CPP and compatibility workarounds were removed
* Most remaining CPP conditions are moved into bytestring-cpp-macros.h and given specific feature names
* Most imports from ghc-prim are replaced with equivalent imports from base
* Data.ByteString.Builder.RealFloat.Internal is left untouched, to avoid unnecessary conflicts
> Remove support for ghc < 8.4

- Data/ByteString.hs
- Data/ByteString/Lazy.hs
The `takeWhileEnd` and `dropWhileEnd` parts are swapped.
> Fix docs for {D.B,D.B.Lazy}.{spanEnd,breakEnd}

- bytestring.cabal
This is useless at best, and a common source of confusion.
https://github.com/haskell/cabal/pull/10145
https://github.com/sol/hpack/issues/355
> Remove `includes` from `.cabal`-file

- .github/workflows/ci.yml
Followed instructions from: https://bitsanddragons.wordpress.com/2024/06/04/fixing-no-urls-in-mirrorlist-error-on-centos-8-stream/
> use vaulted centos packages to fix old-ghc ci

- Data/ByteString/Builder/Internal.hs
Fixes #690.
`toLazyByteString :: Builder -> LazyByteString` had a race condition that could generate wrong results if two threads concurrently evaluated the result.  This bug was introduced in #581 (5c4d23670e32967ad615699b5262e9cba4daccb7) and first present in release 0.11.5.0 (as 0c030bb63999117a6b1cb1275245a156313c0e49).
Due to the use of `unsafeDupablePerformIO` for performance, it is critical that any IO actions executed when running a `Builder` can be interrupted or executed multiple times.  In principle, filling a buffer is safe provided the buffer is used only once and the same bytes are written each time. However, `wrapChunk` in `buildStepToCIOS` would re-use a buffer in the trimming case after copying its contents to produce a new trimmed chunk. This is safe when run in a single …
> Builder: avoid unsound buffer reuse

- .github/workflows/ci.yml
- bytestring.cabal
- cabal.project.wasi
- tests/Lift.hs
- tests/Properties.hs
Draft, just to get feedback from GHA.
> CI: add WASM job

- Data/ByteString/Builder/Internal.hs
As requested in https://github.com/haskell/bytestring/pull/691#pullrequestreview-2304362704, this adds a warning to the documentation of `customStrategy` based on the discussion in #690 indicating that its ability to reuse buffers is generally unsafe in multithreaded programs.
> Improve documentation of customStrategy

- bytestring.cabal
Some combinations of Apple toolchains and GHC versions will provide headers that anger -Werror=undef.  See discussion at that #665.
This is the same condition as in the Hackage revision 0.12.1.0-r1, but I've moved it out of the `else` branch so that it also applies if the pure-haskell flag is set.
> Add a constraint reflecting #665 to the package description

- Data/ByteString/Builder/ASCII.hs
- Data/ByteString/Builder/Prim/ASCII.hs
- Data/ByteString/Internal/Pure.hs
- Data/ByteString/Internal/Type.hs
- cbits/itoa.c
> Use only fixed-width uints in the C itoa functions

- .github/workflows/ci.yml
- Data/ByteString.hs
- Data/ByteString/Lazy.hs
- Data/ByteString/Lazy/Internal.hs
- Data/ByteString/Short/Internal.hs
- README.md
- bench/BenchReadInt.hs
- bytestring.cabal
- include/bytestring-cpp-macros.h
Closes #695. Also related to #707.
> Documentation improvements
