Data/ByteString.hs
Data/ByteString/Internal.hs
Data/ByteString/Lazy.hs
bench/BenchAll.hs
bench/bench-bytestring.cabal

Improve the performance of `partition` for lazy and strict bytestrings

---

Data/ByteString/Builder/Internal.hs
Data/ByteString/Internal.hs
Data/ByteString/Lazy/Internal.hs
Data/ByteString/Short/Internal.hs

See https://github.com/ekmett/semigroups/issues/56 for more details

Define Semigroup instances for base>=4.9

---

tests/Makefile

Replace old -auto-all by -fprof-auto.

Fix: #12084 deprecate old profiling flags

---

Data/ByteString/Lazy.hs

Add documentation for Lazy hPut

---

Data/ByteString/Char8.hs

Fixes #87. Data.ByteString.Char8 should simply re-export the IO functions from Data.ByteString.
This was #88 but force pushing seemed to cause GitHub to close the PR.

Data.ByteString.Char8 uses IO functions exported from Data.ByteString

---

Data/ByteString.hs
Data/ByteString/Unsafe.hs

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

Fix #86, remark on lifetime properties of CString.

---

Data/ByteString.hs

hFileSize only works for regular files and fails for example with /dev/null. However, hFileSize is only used as a hint for how much to read. It should be safe to ignore the exception and try reading the given file anyway.
Fixes #67

Catch IOException from hFileSize in readFile

---

Data/ByteString.hs
Data/ByteString/Lazy.hs

Really saves developer's time.

Add ‘since’ notes to relatively new functions

---

Data/ByteString.hs

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

Haddock fixup.

---

Data/ByteString/Builder/ASCII.hs
Data/ByteString/Builder/Internal.hs
Data/ByteString/Builder/Prim/Internal.hs
Data/ByteString/Internal.hs
Data/ByteString/Lazy/Internal.hs
Data/ByteString/Short/Internal.hs

Use `not-home` instead of `hide` for internal modules

---

Data/ByteString/Builder/Prim/Internal/Floating.hs

Summary:
For links in subpackages as well.
https://phabricator.haskell.org/D5257
Test Plan:
Verify link manually

Fix some broken links (Trac #15733)

---

Data/ByteString/Char8.hs
Data/ByteString/Lazy/Char8.hs

readInt: Document overflowing behaviour.

---

Data/ByteString/Builder/Prim.hs

- Primas -> Prim as
- Need to lift FixedPrim word8 -> BoundedPrim for use with condB

Fix nits in primMapByteStringBounded haddock.

---

Changelog.md
Data/ByteString/Builder/Prim/Binary.hs
Data/ByteString/Builder/Prim/Internal.hs

This is a rebased version of #133

Don't perform unaligned writes (REBASED)

---

.travis.yml

Travis: Build haddocks

---

.travis.yml
bench/BenchAll.hs
bench/BoundsCheckFusion.hs
bench/bench-bytestring.cabal
bench/cabal.project

Improve benchmark ergonomics, test them in CI

---

Data/ByteString.hs

Fixes #200, supersedes #201. I rebased @AndreasPK commit and added review suggestions.

Document possible interleaving of hPutStrLn

---

cbits/fpstring.c

As discussed in #267. 
CC @vdukhovni

Replace unsigned long c with size_t c in fps_count

---

Data/ByteString.hs
tests/bytestring-tests.cabal

- Drop unnecessary import
- Add missing module dependency

Build cleanup

---

Data/ByteString/Lazy.hs

Follow up on #258.
CC @Kleidukos @kozross @vdukhovni @Lysxia

Expand section about lazy I/O

---

.github/workflows/ci.yml

As it has some fixes for windows CI: https://github.com/actions/setup-haskell/releases/tag/v1.1.4

Update setup-haskell GitHub Action

---

Data/ByteString.hs
Data/ByteString/Internal.hs
Data/ByteString/Lazy.hs
bench/BenchAll.hs

…in order to avoid confusion with findIndexEnd.

Rename findIndexOrEnd to findIndexOrLength

---

Data/ByteString/Builder/Prim.hs

Because of upcoming changes in GHC 9.2, it is best to rebox them before
doing anything with them for compatibility without CPP. In particular,
the invariants we can exploit for avoiding CPP are:
- The element types in the array reads and array writes matches
- The element type for the N-width array accesses matches the boxed
N-width type.
The reboxing done here is extremely local so GHC should have no problem
optimizing it away.
CC @bgamari.
Note this will need a 0.11 backport, but no 0.10 backport. It
cherry-picks without conflicts.

Limit use of unboxed elements from array access

---

Changelog.md
Data/ByteString/Builder/Prim.hs
Data/ByteString/Internal.hs

@since annotations for 0.11.0.0

---

bench/BenchAll.hs
bytestring.cabal

Improve benchmarks stability

---

.github/dependabot.yml
.github/workflows/ci.yml

As discussed at https://github.com/haskell/bytestring/pull/384#issuecomment-841651350

Disable dependabot for CI

---

Data/ByteString.hs

Closes #208 as discussed at https://github.com/haskell/bytestring/issues/208#issuecomment-699535007

Remove zipWith rewrite rule

---

.cirrus.yml
.github/workflows/ci.yml

Switch FreeBSD CI to Cirrus

---

.drone.yml

https://cloud.drone.io/Bodigrim/bytestring/15/1/2

Add ARM build

---

Data/ByteString/Lazy.hs
tests/Properties.hs
tests/Properties/ByteString.hs
tests/QuickCheckUtils.hs

Build with 
```cabal
packages: .
tests: True
benchmarks: True
allow-newer:
splitmix:base
packages: ../quickcheck
constraints:
QuickCheck -templateHaskell +old-random
source-repository-package
type: git
location: https://github.com/UnkindPartition/tasty
subdir: core
```

Prepare for monomorphic Data.List

---

Data/ByteString.hs

Expands on conversation in https://github.com/haskell/bytestring/pull/403

Document unsafePerformIO and FilePath conversions.

---

Changelog.md
Data/ByteString/Builder/RealFloat.hs
Data/ByteString/Builder/RealFloat/Internal.hs
Data/ByteString/Builder/RealFloat/TableGenerator.hs
bytestring.cabal
tests/builder/Data/ByteString/Builder/Tests.hs

As discussed in https://github.com/haskell/bytestring/pull/422#issuecomment-918432242, it's time to make a minor release. 
Waiting for #445 to be merged. 
GHC HEAD builds: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7122

Release 0.11.2.0

---

cbits/is-valid-utf8.c

Cherry-picking @bgamari's fix for #475.

Fix unaligned access in is_valid_utf8

---

README.md

This has been out of date for a while.

Update required GHC version in README.md

---

Data/ByteString/Builder.hs
Data/ByteString/Builder/Internal.hs
Data/ByteString/Builder/Prim.hs

Data/ByteString/Builder.hs
Data/ByteString/Builder/Internal.hs
Data/ByteString/Builder/Prim.hs
@Bodigrim missed these in `#501`

fix spelling errors

---

.drone.yml
Data/ByteString.hs
Data/ByteString/Char8.hs
Data/ByteString/Lazy.hs
Data/ByteString/Lazy/Char8.hs

Apparently #259 was lost at some point, so restoring.

Document possible interleaving of hPutStrLn and friends (cf. #259)

---

.cirrus.yml

Update to FreeBSD 13.1 to fix cabal-install

---

.cirrus.yml

Cf. https://github.com/haskell/unix/pull/262

Add OpenBSD and NetBSD CI jobs

---

.cirrus.yml
.github/workflows/ci.yml

* Bump Ubuntu to 22.04 for emulated jobs.
* Bump NetBSD to 9.3.

CI updates

---

.cirrus.yml

...with the hope of un-breaking the FreeBSD job.

Bump versions in .cirrus.yml

---

.cirrus.yml

...with the hope of un-breaking CI.

Bump FreeBSD version in .cirrus.yml

---

bytestring.cabal

Remove -Werror=undef
